import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface DayPlan {
  day: string;
  exercises: {
    name: string;
    sets: string;
    reps: string;
    rest: string;
    tempo?: string;
    cues?: string;
    alternative?: string;
    estimatedTimeMinutes?: number;
    weight_kg?: string;
    notes?: string;
  }[];
}

interface MealPlan {
  meal: string;
  time?: string;
  foods: string[];
  calories: number;
}

interface PlanData {
  programOverview?: string;
  warmUp?: string;
  coolDown?: string;
  weeklySplit?: string[];
  estimatedSessionTimeMinutes?: number;
  progressionRules?: string;
  deloadWeek?: string;
  recoveryTips?: string;
  warnings?: string[];
  workout_plan: DayPlan[];
  meal_plan: MealPlan[];
  calorie_target: number;
  protein: number;
  carbs: number;
  fat: number;
  water_liters: number;
  safety_notes: string[];
  motivational_message: string;
  grocery_list: string[];
  estimated_calories_burned: number;
  weight_projection: string;
}

const GREEN: [number, number, number] = [22, 163, 74];
const DARK = [30, 30, 30] as const;
const GREY = [100, 100, 100] as const;
const LIGHT_GREY = [160, 160, 160] as const;
const ML = 20; // margin left
const MR = 20;
const PW = 210 - ML - MR; // printable width

function drawHeader(doc: jsPDF, page: number, totalPages: number) {
  doc.setPage(page);
  // Logo
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...GREEN);
  doc.text("Surya-FitAi", ML, 14);
  // Right side
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...LIGHT_GREY);
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  doc.text(`Generated by Coach Surya  |  ${dateStr}`, 210 - MR, 14, { align: "right" });
  // Divider
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.5);
  doc.line(ML, 18, 210 - MR, 18);
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...LIGHT_GREY);
  doc.text(`Page ${page} of ${totalPages}`, 105, 290, { align: "center" });
}

export function exportPlanToPDF(plan: PlanData, programType?: string, userName?: string) {
  const doc = new jsPDF();
  let y = 28;

  const check = (need: number) => {
    if (y > 275 - need) { doc.addPage(); y = 28; }
  };

  const sectionTitle = (title: string) => {
    check(16);
    doc.setFillColor(...GREEN);
    doc.roundedRect(ML, y - 5, PW, 10, 1, 1, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(title, ML + 4, y + 1.5);
    y += 12;
  };

  const label = (text: string, x: number, yy: number, size = 8) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(...DARK);
    doc.text(text, x, yy);
  };

  const body = (text: string, x: number, yy: number, maxW = PW, size = 8): number => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(...GREY);
    const lines = doc.splitTextToSize(text, maxW);
    doc.text(lines, x, yy);
    return lines.length;
  };

  // ═══ COVER ═══
  const pType = (programType || "Custom").charAt(0).toUpperCase() + (programType || "custom").slice(1);

  y = 55;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...DARK);
  doc.text(`${pType} Program`, ML, y);
  y += 10;

  if (userName) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(...GREY);
    doc.text(`Prepared for: ${userName}`, ML, y);
    y += 12;
  } else {
    y += 4;
  }

  // Macro info bar
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(ML, y - 4, PW, 14, 2, 2, "F");
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(ML, y - 4, PW, 14, 2, 2, "S");

  const macros = [
    `${plan.calorie_target} kcal`,
    `Protein: ${plan.protein}g`,
    `Carbs: ${plan.carbs}g`,
    `Fat: ${plan.fat}g`,
    `Water: ${plan.water_liters}L`,
  ];
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...GREEN);
  const macroStr = macros.join("   |   ");
  doc.text(macroStr, 105, y + 4, { align: "center" });
  y += 18;

  // Session time
  if (plan.estimatedSessionTimeMinutes) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    doc.text(`Estimated session time: ${plan.estimatedSessionTimeMinutes} minutes (includes warm-up and cool-down)`, ML, y);
    y += 8;
  }

  // Motivational message
  if (plan.motivational_message) {
    check(20);
    doc.setFillColor(248, 248, 248);
    const msgLines = doc.splitTextToSize(plan.motivational_message, PW - 12);
    const boxH = msgLines.length * 4.5 + 8;
    doc.roundedRect(ML, y - 4, PW, boxH, 2, 2, "F");
    doc.setFillColor(...GREEN);
    doc.rect(ML, y - 4, 3, boxH, "F");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(msgLines, ML + 8, y + 2);
    y += boxH + 6;
  }

  // Program Overview
  if (plan.programOverview) {
    check(20);
    label("PROGRAM OVERVIEW", ML, y, 9);
    y += 5;
    const lines = body(plan.programOverview, ML, y, PW, 8);
    y += lines * 4 + 6;
  }

  // ═══ WARM-UP ═══
  if (plan.warmUp) {
    check(20);
    label("WARM-UP", ML, y, 10);
    y += 5;
    const lines = body(plan.warmUp, ML, y, PW);
    y += lines * 4 + 6;
  }

  // ═══ WORKOUT PLAN ═══
  if (plan.workout_plan?.length) {
    check(14);
    sectionTitle("WORKOUT PLAN");

    for (const day of plan.workout_plan) {
      check(18);

      // Day header
      doc.setFillColor(240, 253, 244);
      doc.roundedRect(ML, y - 4, PW, 9, 1, 1, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...GREEN);
      doc.text(day.day, ML + 4, y + 2);
      y += 10;

      if (day.exercises.length === 0) {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        doc.setTextColor(...GREY);
        doc.text("Rest & Recovery Day", ML + 4, y);
        y += 8;
        continue;
      }

      for (let ei = 0; ei < day.exercises.length; ei++) {
        const ex = day.exercises[ei];
        check(28);

        // Exercise name
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(...DARK);
        doc.text(ex.name, ML + 2, y);
        y += 4.5;

        // Sets x Reps | Rest | Tempo
        const meta = `${ex.sets} x ${ex.reps}  |  Rest: ${ex.rest}${ex.tempo ? `  |  Tempo: ${ex.tempo}` : ""}`;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...GREY);
        doc.text(meta, ML + 2, y);
        y += 4.5;

        // Weight
        if (ex.weight_kg) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(8);
          doc.setTextColor(...GREEN);
          doc.text(`Weight: ${ex.weight_kg}`, ML + 2, y);
          y += 4;
        }

        // Tips
        if (ex.cues) {
          doc.setFont("helvetica", "italic");
          doc.setFontSize(7.5);
          doc.setTextColor(120, 120, 120);
          const cueLines = doc.splitTextToSize(`Tips: ${ex.cues}`, PW - 6);
          doc.text(cueLines, ML + 6, y);
          y += cueLines.length * 3.5;
        }

        // Alternative
        if (ex.alternative) {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(7.5);
          doc.setTextColor(...LIGHT_GREY);
          doc.text(`Alternative: ${ex.alternative}`, ML + 6, y);
          y += 3.5;
        }

        // Notes
        if (ex.notes) {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(7.5);
          doc.setTextColor(...LIGHT_GREY);
          const noteLines = doc.splitTextToSize(`Notes: ${ex.notes}`, PW - 6);
          doc.text(noteLines, ML + 6, y);
          y += noteLines.length * 3.5;
        }

        // Divider between exercises
        if (ei < day.exercises.length - 1) {
          y += 2;
          doc.setDrawColor(230, 230, 230);
          doc.setLineWidth(0.2);
          doc.line(ML + 2, y, 210 - MR - 2, y);
          y += 4;
        } else {
          y += 4;
        }
      }
      y += 2;
    }
  }

  // ═══ COOL-DOWN ═══
  if (plan.coolDown) {
    check(20);
    label("COOL-DOWN", ML, y, 10);
    y += 5;
    const lines = body(plan.coolDown, ML, y, PW);
    y += lines * 4 + 6;
  }

  // ═══ MEAL PLAN ═══
  if (plan.meal_plan?.length) {
    check(20);
    sectionTitle("MEAL PLAN");

    const mealRows = plan.meal_plan.map((m) => [
      m.meal + (m.time ? `\n${m.time}` : ""),
      m.foods.join(", "),
      `${m.calories} kcal`,
    ]);

    const totalCals = plan.meal_plan.reduce((sum, m) => sum + m.calories, 0);
    mealRows.push(["TOTAL", "", `${totalCals} kcal`]);

    autoTable(doc, {
      startY: y,
      head: [["Meal", "Foods", "Calories"]],
      body: mealRows,
      theme: "striped",
      headStyles: {
        fillColor: GREEN as any,
        textColor: [255, 255, 255],
        fontSize: 9,
        font: "helvetica",
        fontStyle: "bold",
      },
      bodyStyles: { fontSize: 8, textColor: DARK as any, font: "helvetica" },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      columnStyles: { 0: { cellWidth: 35, fontStyle: "bold" }, 1: { cellWidth: 110 }, 2: { cellWidth: 25, halign: "right" } },
      margin: { left: ML, right: MR },
      didParseCell: (data) => {
        if (data.section === "body" && data.row.index === mealRows.length - 1) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.fillColor = [240, 253, 244];
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ═══ GROCERY LIST ═══
  if (plan.grocery_list?.length) {
    check(20);
    sectionTitle("GROCERY LIST");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...DARK);
    const cols = 3;
    const colW = Math.floor(PW / cols);
    plan.grocery_list.forEach((item, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      if (col === 0 && row > 0) check(5);
      doc.text(`- ${item}`, ML + col * colW, y + row * 5);
    });
    y += Math.ceil(plan.grocery_list.length / cols) * 5 + 8;
  }

  // ═══ INFO SECTIONS ═══
  const infoSections: [string, string | undefined][] = [
    ["PROGRESSION RULES", plan.progressionRules],
    ["DELOAD WEEK", plan.deloadWeek],
    ["RECOVERY TIPS", plan.recoveryTips],
  ];

  for (const [title, content] of infoSections) {
    if (!content) continue;
    check(22);
    doc.setFillColor(248, 248, 248);
    const cLines = doc.splitTextToSize(content, PW - 12);
    const bH = cLines.length * 4 + 12;
    doc.roundedRect(ML, y - 4, PW, bH, 2, 2, "F");
    label(title, ML + 6, y + 2, 9);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...GREY);
    doc.text(cLines, ML + 6, y);
    y += cLines.length * 4 + 8;
  }

  // ═══ SAFETY & WARNINGS ═══
  const allWarnings = [...(plan.warnings || []), ...(plan.safety_notes || [])];
  if (allWarnings.length) {
    check(22);
    doc.setFillColor(255, 243, 224);
    const warningText = allWarnings.join("\n\n");
    const wLines = doc.splitTextToSize(warningText, PW - 12);
    const wH = wLines.length * 4 + 14;
    doc.roundedRect(ML, y - 4, PW, wH, 2, 2, "F");
    doc.setFillColor(251, 146, 60);
    doc.rect(ML, y - 4, 3, wH, "F");
    label("SAFETY & WARNINGS", ML + 8, y + 2, 9);
    y += 9;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 60, 20);
    doc.text(wLines, ML + 8, y);
    y += wLines.length * 4 + 8;
  }

  // ═══ HEADERS & FOOTERS ═══
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    drawHeader(doc, i, totalPages);
  }

  doc.save(`Surya-FitAi-${(programType || "plan").replace(/\s/g, "-")}-plan.pdf`);
}
