import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface DayPlan {
  day: string;
  exercises: { name: string; sets: string; reps: string; rest: string }[];
}

interface MealPlan {
  meal: string;
  foods: string[];
  calories: number;
}

interface PlanData {
  workout_plan: DayPlan[];
  meal_plan: MealPlan[];
  calorie_target: number;
  protein: number;
  carbs: number;
  fat: number;
  water_liters: number;
  safety_notes: string[];
  motivational_message: string;
  grocery_list: string[];
  estimated_calories_burned: number;
  weight_projection: string;
}

export function exportPlanToPDF(plan: PlanData, programType?: string, userName?: string) {
  const doc = new jsPDF();
  const green = [57, 255, 20] as const;
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(...green);
  doc.text("FitAI", 14, y);
  doc.setFontSize(12);
  doc.setTextColor(150, 150, 150);
  doc.text(`${(programType || "Custom").charAt(0).toUpperCase() + (programType || "custom").slice(1)} Program`, 14, y + 8);
  if (userName) doc.text(`Prepared for: ${userName}`, 14, y + 14);
  y += userName ? 24 : 18;

  // Macros summary
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  doc.text(`Daily Target: ${plan.calorie_target} kcal  |  Protein: ${plan.protein}g  |  Carbs: ${plan.carbs}g  |  Fat: ${plan.fat}g  |  Water: ${plan.water_liters}L`, 14, y);
  y += 10;

  // Workout plan
  if (plan.workout_plan?.length) {
    doc.setFontSize(14);
    doc.setTextColor(...green);
    doc.text("Workout Plan", 14, y);
    y += 4;

    for (const day of plan.workout_plan) {
      const rows = day.exercises.map((ex) => [ex.name, ex.sets, ex.reps, ex.rest]);
      autoTable(doc, {
        startY: y,
        head: [[day.day, "Sets", "Reps", "Rest"]],
        body: rows,
        theme: "grid",
        headStyles: { fillColor: [30, 30, 30], textColor: green as any, fontSize: 9 },
        bodyStyles: { fontSize: 8, textColor: [60, 60, 60] },
        margin: { left: 14, right: 14 },
        tableWidth: "auto",
      });
      y = (doc as any).lastAutoTable.finalY + 4;
      if (y > 260) { doc.addPage(); y = 20; }
    }
  }

  // Meal plan
  if (plan.meal_plan?.length) {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setTextColor(...green);
    doc.text("Meal Plan", 14, y);
    y += 4;

    const mealRows = plan.meal_plan.map((m) => [m.meal, m.foods.join(", "), `${m.calories} kcal`]);
    autoTable(doc, {
      startY: y,
      head: [["Meal", "Foods", "Calories"]],
      body: mealRows,
      theme: "grid",
      headStyles: { fillColor: [30, 30, 30], textColor: green as any, fontSize: 9 },
      bodyStyles: { fontSize: 8, textColor: [60, 60, 60] },
      columnStyles: { 1: { cellWidth: 110 } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Grocery list
  if (plan.grocery_list?.length) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setTextColor(...green);
    doc.text("Grocery List", 14, y);
    y += 6;
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const cols = 3;
    const colWidth = 60;
    plan.grocery_list.forEach((item, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      doc.text(`• ${item}`, 14 + col * colWidth, y + row * 5);
    });
    y += Math.ceil(plan.grocery_list.length / cols) * 5 + 6;
  }

  // Safety notes
  if (plan.safety_notes?.length) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setTextColor(...green);
    doc.text("Safety Notes", 14, y);
    y += 6;
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    plan.safety_notes.forEach((note) => {
      if (y > 280) { doc.addPage(); y = 20; }
      const lines = doc.splitTextToSize(`⚠ ${note}`, 180);
      doc.text(lines, 14, y);
      y += lines.length * 4.5;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text(`Generated by FitAI — ${new Date().toLocaleDateString()}`, 14, 290);

  doc.save(`FitAI-${(programType || "plan").replace(/\s/g, "-")}-plan.pdf`);
}
