import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "id" | "zh";

const translations = {
  en: {
    // Common
    back: "Back",
    backToPrograms: "Back to Programs",
    home: "Home",

    // Nav
    myPlans: "My Plans",
    progress: "Progress",
    signOut: "Sign Out",
    signIn: "Sign In",

    // Hero
    aiPowered: "AI-Powered Training",
    heroTitle1: "Your Personal",
    heroTitle2: "Smart Coach",
    heroDesc: "Get a fully personalized workout plan, nutrition guide, and grocery list — generated in seconds by Coach Surya, tailored to your body and goals.",
    startProgram: "Start My Program",

    // Features
    howItWorks: "How It",
    works: "Works",
    feature1Title: "Choose Your Program",
    feature1Desc: "Pick from Beginner, Bulking, Cutting, or Senior fitness programs tailored to your needs.",
    feature2Title: "AI Analyzes You",
    feature2Desc: "Our AI engine processes your body data, goals, and limitations to create the perfect plan.",
    feature3Title: "Get Your Plan",
    feature3Desc: "Receive a complete workout schedule, meal plan, grocery list, and progress targets.",

    // CTA
    readyTransform: "Ready to Transform?",
    ctaDesc: "Join thousands who already use AI to reach their fitness goals faster.",
    getStarted: "Get Started Free",

    // Footer
    rights: "© 2026 All rights reserved",

    // Programs page
    chooseYour: "Choose Your",
    program: "Program",
    programsDesc: "Select the program that matches your fitness goals. Our AI will create a fully personalized plan for you.",

    // Program cards
    beginnerTitle: "Beginner Program",
    beginnerDesc: "Perfect for those new to gym and healthy lifestyle. Build a solid foundation with guided exercises.",
    beginnerBenefits: ["Learn proper form", "Build basic strength", "Establish routine", "Nutrition basics"],
    beginnerGoal: "Build fitness foundation",
    bulkingTitle: "Bulking Program",
    bulkingDesc: "Maximize muscle gain and mass building with high-volume training and caloric surplus plans.",
    bulkingBenefits: ["Muscle hypertrophy", "Progressive overload", "High protein meals", "Recovery optimization"],
    bulkingGoal: "Build muscle mass",
    cuttingTitle: "Cutting Program",
    cuttingDesc: "Shed body fat while preserving muscle. Get defined and lean with strategic training and nutrition.",
    cuttingBenefits: ["Fat loss focus", "Maintain muscle", "Calorie deficit meals", "HIIT integration"],
    cuttingGoal: "Lose fat and get lean",
    seniorTitle: "Senior Fitness",
    seniorDesc: "Safe, adaptive workouts designed for older adults. Focus on mobility, balance, and functional strength.",
    seniorBenefits: ["Joint-friendly exercises", "Balance training", "Flexibility focus", "Safe progression"],
    seniorGoal: "Improve mobility and strength",

    // ProgramForm
    tellUs: "Tell us about yourself so our AI can create your personalized plan.",
    fullName: "Full Name *",
    age: "Age *",
    gender: "Gender *",
    genderSelect: "Select",
    male: "Male",
    female: "Female",
    other: "Other",
    weightKg: "Weight (kg) *",
    heightCm: "Height (cm) *",
    fitnessGoal: "Fitness Goal",
    fitnessGoalPlaceholder: "Build fitness foundation / Lose fat & build muscle",
    trainingDuration: "Training Duration",
    experienceLevel: "Experience Level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    weeks2: "2 Weeks",
    month1: "1 Month",
    months3: "3 Months",
    limitations: "Physical Limitations or Injuries (optional)",
    limitationsPlaceholder: "E.g., knee injury, lower back pain...",
    allergies: "Food Allergies (optional)",
    allergiesPlaceholder: "E.g., nuts, dairy, gluten...",
    generatePlan: "Generate My Plan",
    generating: "Generating Your Plan...",
    generatingStep1: "Analyzing your profile...",
    generatingStep2: "Building your workout plan...",
    generatingStep3: "Crafting your meal plan...",
    generatingStep4: "Finalizing your blueprint...",
    fillRequired: "Please fill all required fields",
    planErrTimeout: "This plan is taking longer than expected. Please tap 'Generate My Plan' again to retry.",
    planErrParse: "We had trouble reading the AI response. Please tap 'Generate My Plan' again to retry.",
    planErrInternal: "Something went wrong. Please try again in a moment.",
    planErrNetwork: "Connection error. Please check your internet and try again.",
    planErrRate: "Too many requests right now. Please wait a moment and try again.",
    planErrCredits: "AI usage limit reached. Please contact support.",
    retry: "Retry",
    trainingStartDate: "Training Start Date *",
    pickDate: "Pick a date",

    // Food Style
    foodStyleLabel: "Food Source Style *",
    foodStylePlaceholder: "Select food style",
    foodStyleLocal: "Local Traditional Foods (based on my country)",
    foodStyleWestern: "Western Style",
    foodStyleAsian: "Asian Style",
    foodStyleHighProtein: "High-Protein Fitness Style",
    foodStyleBudget: "Budget-Friendly Local Foods",
    foodStylePremium: "Premium / Whole Foods Focus",

    // Results
    yourPersonalized: "Your Custom",
    aiPlan: "Training Blueprint",
    heyUser: "Hey {name}! Here's your custom {type} program.",
    hereCustom: "Here's your custom {type} program.",
    dailyCalories: "Daily Calories",
    protein: "Protein",
    carbsFat: "Carbs / Fat",
    water: "Water",
    exportPdf: "Export PDF",
    savePlan: "Save Plan",
    saved: "Saved",
    signInToSave: "Sign in to save your plan",
    signInToSaveDesc: "Create an account to save and access your plans anytime.",
    planSaved: "Plan saved!",
    errorSaving: "Error saving plan",
    workoutPlan: "Workout Plan",
    mealPlan: "Meal Plan",
    groceryList: "Grocery List",
    infoSafety: "Info & Safety",
    weeklyGrocery: "Weekly Grocery List",
    progressProjection: "Progress Projection",
    safetyNotes: "Safety Notes",
    weeklySchedule: "Weekly Schedule Overview",
    estimatedCalories: "Estimated {count} calories burned per session",
    noPlanData: "No plan data found.",
    goBackPrograms: "Go back to programs",
    rest: "rest",
    done: "done",
    progressTab: "Progress",

    // Progress
    progressTracker: "Progress",
    tracker: "Tracker",
    progressDesc: "Log your weekly weigh-ins and track your transformation.",
    start: "Start",
    current: "Current",
    change: "Change",
    weightOverTime: "Weight Over Time",
    logAtLeast2: "Log at least 2 check-ins to see your progress chart.",
    logCheckIn: "Log Check-In",
    date: "Date",
    weightLabel: "Weight (kg)",
    noteOptional: "Note (optional)",
    notePlaceholder: "Feeling great!",
    addCheckIn: "Add Check-In",
    checkInLogged: "Check-in logged!",
    validWeight: "Enter a valid weight (20–500 kg)",
    history: "History",

    // Workout Activity
    workoutActivity: "Workout Activity",
    today: "Today",
    exercises: "exercises",
    streak: "Streak",
    day: "day",
    days: "days",
    thisWeek: "This Week",
    total: "total",
    activeDays: "Active Days",
    noCompletions: "No workout completions yet. Save a plan and start checking off exercises!",
    completed: "Completed",

    // Auth
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    signInAccess: "Sign in to access your saved plans",
    signUpSave: "Sign up to save your plans and track progress",
    displayName: "Display Name",
    email: "Email *",
    password: "Password *",
    signUp: "Sign Up",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    welcomeBackToast: "Welcome back!",
    accountCreated: "Account created!",
    checkEmail: "Please check your email to verify your account.",

    // Saved Plans
    savedPlans: "Saved",
    plans: "Plans",
    savedPlansDesc: "Your previously generated AI fitness plans.",
    noSavedPlans: "No saved plans yet.",
    generateFirst: "Generate Your First Plan",
    view: "View",
    planDeleted: "Plan deleted",
    planRenamed: "Plan renamed",
    addPlan: "+ Add Plan",
    whatsappCta: "Get Personal Trainer Assistance from Coach Surya",
    occupation: "Occupation",
    occupationSelect: "Select occupation",
    occupationStudent: "Student",
    occupationOffice: "Office Worker (Mostly Sitting)",
    occupationField: "Field Worker (Physically Active)",
    occupationFreelancer: "Freelancer",
    occupationBusiness: "Business Owner",
    occupationOtherPlaceholder: "Enter your occupation",
    trainingFrequency: "Training Days / Week",
    freq2: "2 Days",
    freq3: "3 Days",
    freq4: "4 Days",
    freq5: "5 Days",
    freq6: "6 Days",
    freq7: "7 Days",
    downloadProgress: "Download Progress",
    shareProgress: "Share",
    delete: "Delete",
    confirmDelete: "Are you sure?",

    // Settings
    settingsLanguage: "Language",
    active: "Active",
    inactive: "Inactive",
    switchPlan: "Switch to this plan",
    createNewPlan: "Create New Plan",
    noPlansYet: "No plans yet. Create your first AI fitness plan!",
    planSwitched: "Plan switched!",
    languageChanged: "Language changed!",
    duration: "Duration",
    foodStyle: "Food Style",

    // ProgressDownloadCard
    progressReport: "Progress Report",
    nameLabel: "Name",
    programLabel: "Program",
    durationLabel: "Duration",
    weightLabelShort: "Weight",
    bmiLabel: "BMI",
    calorieTargetLabel: "Calorie Target",
    motCompleted: "You Built This. Discipline Wins. 🔥",
    motInProgress: "Keep pushing towards your goals! 💪",
    eliteCompleted: "🏆 ELITE COMPLETED",
    consistency: "Consistency",
    generatedBy: "Generated by Surya-FitAi",
    copied: "Copied!",
    copyCaption: "Copy Caption",
    failedToSave: "Failed to save",

    // NotFound
    notFoundTitle: "404",
    notFoundDesc: "Oops! Page not found",
    returnHome: "Return to Home",

    // Enhanced Form - Sections
    basicInfoSection: "Personal Information",
    trainingConfigSection: "Training Configuration",
    lifestyleSection: "Lifestyle & Recovery",
    nutritionSection: "Nutrition Preferences",

    // Enhanced Form - Why tooltip header
    whyWeAsk: "Why we ask this?",

    // Enhanced Form - Session Duration
    sessionDurationLabel: "Session Duration (minutes)",
    whySessionDuration: "This helps us calculate the exact number of exercises and sets so your workout fits perfectly in the time you have available. 60 minutes is ideal for most people.",
    minutes: "min",

    // Enhanced Form - Equipment
    equipmentLabel: "Available Equipment",
    whyEquipment: "We will only suggest exercises you can actually do with the equipment you have at home or gym. Choose all that apply.",
    equipBodyweight: "Bodyweight Only",
    equipDumbbell: "Dumbbell Only",
    equipFullGym: "Full Gym",
    equipHomeBarbell: "Home Gym + Barbell",
    equipBands: "Resistance Bands",
    equipNone: "None",

    // Enhanced Form - Daily Steps
    dailyStepsLabel: "Daily Steps / Activity Level",
    whyDailySteps: "Your daily activity affects calorie needs (NEAT). More steps = higher TDEE.",
    steps0: "< 4,000 steps (Sedentary)",
    steps1: "4,000 – 8,000 steps (Light)",
    steps2: "8,000 – 12,000 steps (Moderate)",
    steps3: "> 12,000 steps (Very Active)",
    stepsDesk: "Desk job 8+ hours",

    // Enhanced Form - Sleep
    sleepHoursLabel: "Average Sleep (hours)",
    whySleep: "Sleep quality affects recovery, hormone balance, and training capacity.",
    sleepQualityLabel: "Sleep Quality",

    // Enhanced Form - Stress
    stressLevelLabel: "Current Stress Level",
    whyStress: "High stress increases cortisol, requiring adjusted volume and recovery.",
    nightShiftLabel: "Night shift / overtime work",

    // Enhanced Form - Nutrition
    mealFrequencyLabel: "Preferred Meal Frequency",
    meals3: "3 meals/day",
    meals4: "4 meals/day",
    meals5: "5 meals/day",
    meals6: "6 meals/day",
    ifLabel: "16/8 Intermittent Fasting",
    whyIF: "Eating window 12:00 PM – 8:00 PM. Helps fat loss and insulin sensitivity.",

    // Enhanced Form - Live Metrics
    liveMetricsTitle: "Your Calculated Metrics",
    targetCalories: "Target Cal",
    carbsLabel: "Carbs",
    fatLabel: "Fat",
    bmiCatUnderweight: "Underweight",
    bmiCatNormal: "Normal",
    bmiCatOverweight: "Overweight",
    bmiCatObese: "Obese",

    // Diet Type
    dietTypeLabel: "Diet Type *",
    dietTypePlaceholder: "Select diet type",
    dietOmnivore: "Omnivore",
    dietVegetarian: "Vegetarian",
    dietVegan: "Vegan",

    // Week Selector
    selectWeekLabel: "Select Week",
    weekLabel: "Week",

    // Exercise Detail Popup
    tipsLabel: "Tips",
    weightRecommendation: "Weight Recommendation",
    notesLabel: "Notes",
    restDayTitle: "Rest & Recovery",
    restDayTip: "Focus on mobility, nutrition, or light walks today.",

    // Enhanced Results
    sessionTimeBanner: "Session time matched: {minutes} minutes (5 min warm-up + lifting + 5 min cool-down)",
    warmUpLabel: "Warm-Up",
    coolDownLabel: "Cool-Down",
    weeklySplitLabel: "Weekly Split",
    tempoLabel: "Tempo",
    alternativeLabel: "Alternative",
    warningsLabel: "Warnings",
    recoveryTipsLabel: "Recovery Tips",
    deloadWeekLabel: "Deload Week",
    progressionRulesLabel: "Progression Rules",
    programDuration: "Program Duration",
    weeksLabel: "weeks",
    draftRestored: "Recovered your last generated plan.",

    // Coach Surya persona
    coachCertified: "Certified Personal Trainer",
    coachExperience: "🌏 10+ Years • Global Clients",
    coachSubtitle: "Designed by Coach Surya — trusted by clients across Southeast Asia & beyond.",
    programsDescCoach: "Each program is personally designed by Coach Surya, built on deep expertise in fitness coaching and nutrition planning. Select the one that matches your goal.",
    coachProgramPill: "Coach Surya • Certified Personal Trainer",
    coachFormIntro: "Coach Surya needs these details to build your perfect plan. The more accurate your information, the more precisely your program will be calibrated to your body and lifestyle.",
    coachMetricsSubtitle: "Coach Surya will use these numbers to calibrate your exact training and nutrition targets.",
    coachGenerateHelper: "Coach Surya's AI will analyze all your data and build a plan calibrated specifically for you",
    coachPreparedBy: "Prepared by Coach Surya",
    coachCredential: "Certified PT & Sports Nutritionist",
    coachCardTitle: "Coach Surya",
    coachCardSubtitle: "Personal Trainer & Sports Nutritionist",
    coachCalibration: "⚙️ Coach's Program Calibration",
    coachWeeklySplitSub: "Coach Surya's recommended training structure for your goals and schedule",
    coachWorkoutActivitySub: "Coach Surya is tracking your consistency. Every session counts.",
    coachProgressionLabel: "Coach Surya's Progressive Overload Protocol",
    coachCompletedDay: "💪 Great work! Coach Surya is proud of your consistency.",
    coachRestTip: "— Coach Surya recommends: hydrate well and prioritize sleep tonight.",
    coachProgressMonitor: "Coach Surya is monitoring your progress throughout this program.",
    coachWeightChartSub: "Log your weight regularly so Coach Surya can track your real progress.",
    coachCheckInSub: "Your check-in data helps Coach Surya calibrate your plan over time.",
    coachHistorySub: "Your progress journey tracked by Coach Surya.",
    whatsappCtaCoach: "Get 1-on-1 Coaching from Coach Surya",
    monthlyPlanHelper: "Program starts at 1 month. After completion, you can extend to the next month or start fresh.",
    monthBadge: "Month",
    activePlanWarning: "You have an active plan in progress. Complete it first or choose a different plan slot.",
    extendingPlan: "Generating your next month plan...",
    extendError: "Failed to extend plan. Please try again.",
    activeBadgeLabel: "In Progress",
    completedBadgeLabel: "Completed",
  },
  id: {
    // Common
    back: "Kembali",
    backToPrograms: "Kembali ke Program",
    home: "Beranda",

    // Nav
    myPlans: "Rencana Saya",
    progress: "Progres",
    signOut: "Keluar",
    signIn: "Masuk",

    // Hero
    aiPowered: "Latihan Berbasis AI",
    heroTitle1: "Pelatih Personal",
    heroTitle2: "Cerdas Anda",
    heroDesc: "Dapatkan rencana latihan, panduan nutrisi, dan daftar belanja yang sepenuhnya dipersonalisasi — dibuat dalam hitungan detik oleh Coach Surya, disesuaikan dengan tubuh dan tujuanmu.",
    startProgram: "Mulai Program",

    // Features
    howItWorks: "Cara",
    works: "Kerjanya",
    feature1Title: "Pilih Program",
    feature1Desc: "Pilih dari program Pemula, Bulking, Cutting, atau Lansia yang disesuaikan dengan kebutuhanmu.",
    feature2Title: "AI Menganalisis Kamu",
    feature2Desc: "Mesin AI kami memproses data tubuh, tujuan, dan batasanmu untuk membuat rencana yang sempurna.",
    feature3Title: "Dapatkan Rencanamu",
    feature3Desc: "Terima jadwal latihan lengkap, rencana makan, daftar belanja, dan target progres.",

    // CTA
    readyTransform: "Siap Berubah?",
    ctaDesc: "Bergabung dengan ribuan orang yang sudah menggunakan AI untuk mencapai tujuan kebugaran lebih cepat.",
    getStarted: "Mulai Gratis",

    // Footer
    rights: "© 2026 Hak cipta dilindungi",

    // Programs page
    chooseYour: "Pilih",
    program: "Program",
    programsDesc: "Pilih program yang sesuai dengan tujuan kebugaranmu. AI kami akan membuat rencana yang sepenuhnya dipersonalisasi untukmu.",

    // Program cards
    beginnerTitle: "Program Pemula",
    beginnerDesc: "Cocok untuk yang baru mengenal gym dan gaya hidup sehat. Bangun fondasi kuat dengan latihan terbimbing.",
    beginnerBenefits: ["Pelajari teknik benar", "Bangun kekuatan dasar", "Bangun rutinitas", "Dasar nutrisi"],
    beginnerGoal: "Bangun fondasi kebugaran",
    bulkingTitle: "Program Bulking",
    bulkingDesc: "Maksimalkan pertumbuhan otot dengan latihan volume tinggi dan rencana surplus kalori.",
    bulkingBenefits: ["Hipertrofi otot", "Beban progresif", "Makanan tinggi protein", "Optimasi pemulihan"],
    bulkingGoal: "Bangun massa otot",
    cuttingTitle: "Program Cutting",
    cuttingDesc: "Turunkan lemak tubuh sambil menjaga otot. Dapatkan tubuh ramping dengan latihan dan nutrisi strategis.",
    cuttingBenefits: ["Fokus pembakaran lemak", "Pertahankan otot", "Makanan defisit kalori", "Integrasi HIIT"],
    cuttingGoal: "Turunkan lemak dan jadi ramping",
    seniorTitle: "Kebugaran Lansia",
    seniorDesc: "Latihan aman dan adaptif untuk orang dewasa. Fokus pada mobilitas, keseimbangan, dan kekuatan fungsional.",
    seniorBenefits: ["Latihan ramah sendi", "Latihan keseimbangan", "Fokus fleksibilitas", "Progres aman"],
    seniorGoal: "Tingkatkan mobilitas dan kekuatan",

    // ProgramForm
    tellUs: "Ceritakan tentang dirimu agar AI kami bisa membuat rencana yang dipersonalisasi.",
    fullName: "Nama Lengkap *",
    age: "Usia *",
    gender: "Jenis Kelamin *",
    genderSelect: "Pilih",
    male: "Laki-laki",
    female: "Perempuan",
    other: "Lainnya",
    weightKg: "Berat Badan (kg) *",
    heightCm: "Tinggi Badan (cm) *",
    fitnessGoal: "Tujuan Kebugaran",
    fitnessGoalPlaceholder: "Membangun fondasi kebugaran / Turunkan lemak & bangun otot",
    trainingDuration: "Durasi Latihan",
    experienceLevel: "Tingkat Pengalaman",
    beginner: "Pemula",
    intermediate: "Menengah",
    advanced: "Mahir",
    weeks2: "2 Minggu",
    month1: "1 Bulan",
    months3: "3 Bulan",
    limitations: "Keterbatasan Fisik atau Cedera (opsional)",
    limitationsPlaceholder: "Contoh: cedera lutut, nyeri punggung bawah...",
    allergies: "Alergi Makanan (opsional)",
    allergiesPlaceholder: "Contoh: kacang, susu, gluten...",
    generatePlan: "Buat Rencana Saya",
    generating: "Membuat Rencanamu...",
    generatingStep1: "Menganalisis profil Anda...",
    generatingStep2: "Menyusun program latihan...",
    generatingStep3: "Merancang rencana makan...",
    generatingStep4: "Menyelesaikan blueprint Anda...",
    fillRequired: "Harap isi semua kolom wajib",
    planErrTimeout: "Pembuatan rencana membutuhkan waktu lebih lama. Silakan tap 'Buat Rencana Saya' lagi untuk mencoba ulang.",
    planErrParse: "Terjadi kendala membaca respons AI. Silakan tap 'Buat Rencana Saya' lagi untuk mencoba ulang.",
    planErrInternal: "Terjadi kesalahan. Silakan coba lagi sebentar.",
    planErrNetwork: "Gagal terhubung. Periksa koneksi internet Anda.",
    planErrRate: "Terlalu banyak permintaan saat ini. Tunggu sebentar lalu coba lagi.",
    planErrCredits: "Batas penggunaan AI tercapai. Silakan hubungi dukungan.",
    retry: "Coba Lagi",
    trainingStartDate: "Tanggal Mulai Latihan *",
    pickDate: "Pilih tanggal",

    // Food Style
    foodStyleLabel: "Gaya Sumber Makanan *",
    foodStylePlaceholder: "Pilih gaya makanan",
    foodStyleLocal: "Makanan Tradisional Lokal (sesuai negara saya)",
    foodStyleWestern: "Gaya Barat",
    foodStyleAsian: "Gaya Asia",
    foodStyleHighProtein: "Gaya Tinggi Protein Fitness",
    foodStyleBudget: "Makanan Lokal Hemat",
    foodStylePremium: "Premium / Fokus Whole Foods",

    // Results
    yourPersonalized: "Program Latihan",
    aiPlan: "Khusus Anda",
    heyUser: "Hai {name}! Ini program {type} khususmu.",
    hereCustom: "Ini program {type} khususmu.",
    dailyCalories: "Kalori Harian",
    protein: "Protein",
    carbsFat: "Karbo / Lemak",
    water: "Air",
    exportPdf: "Ekspor PDF",
    savePlan: "Simpan Rencana",
    saved: "Tersimpan",
    signInToSave: "Masuk untuk menyimpan rencana",
    signInToSaveDesc: "Buat akun untuk menyimpan dan mengakses rencanamu kapan saja.",
    planSaved: "Rencana tersimpan!",
    errorSaving: "Gagal menyimpan rencana",
    workoutPlan: "Rencana Latihan",
    mealPlan: "Rencana Makan",
    groceryList: "Daftar Belanja",
    infoSafety: "Info & Keamanan",
    weeklyGrocery: "Daftar Belanja Mingguan",
    progressProjection: "Proyeksi Progres",
    safetyNotes: "Catatan Keamanan",
    weeklySchedule: "Jadwal Mingguan",
    estimatedCalories: "Estimasi {count} kalori terbakar per sesi",
    noPlanData: "Data rencana tidak ditemukan.",
    goBackPrograms: "Kembali ke program",
    rest: "istirahat",
    done: "selesai",
    progressTab: "Progres",

    // Progress
    progressTracker: "Progres",
    tracker: "Tracker",
    progressDesc: "Catat timbangan mingguanmu dan pantau transformasimu.",
    start: "Awal",
    current: "Saat Ini",
    change: "Perubahan",
    weightOverTime: "Berat Badan Seiring Waktu",
    logAtLeast2: "Catat minimal 2 check-in untuk melihat grafik progresmu.",
    logCheckIn: "Catat Check-In",
    date: "Tanggal",
    weightLabel: "Berat (kg)",
    noteOptional: "Catatan (opsional)",
    notePlaceholder: "Merasa luar biasa!",
    addCheckIn: "Tambah Check-In",
    checkInLogged: "Check-in tercatat!",
    validWeight: "Masukkan berat valid (20–500 kg)",
    history: "Riwayat",

    // Workout Activity
    workoutActivity: "Aktivitas Latihan",
    today: "Hari Ini",
    exercises: "latihan",
    streak: "Streak",
    day: "hari",
    days: "hari",
    thisWeek: "Minggu Ini",
    total: "total",
    activeDays: "Hari Aktif",
    noCompletions: "Belum ada latihan selesai. Simpan rencana dan mulai centang latihanmu!",
    completed: "Selesai",

    // Auth
    welcomeBack: "Selamat Datang Kembali",
    createAccount: "Buat Akun",
    signInAccess: "Masuk untuk mengakses rencana tersimpanmu",
    signUpSave: "Daftar untuk menyimpan rencana dan melacak progres",
    displayName: "Nama Tampilan",
    email: "Email *",
    password: "Kata Sandi *",
    signUp: "Daftar",
    dontHaveAccount: "Belum punya akun?",
    alreadyHaveAccount: "Sudah punya akun?",
    welcomeBackToast: "Selamat datang kembali!",
    accountCreated: "Akun dibuat!",
    checkEmail: "Silakan cek emailmu untuk verifikasi akun.",

    // Saved Plans
    savedPlans: "Rencana",
    plans: "Tersimpan",
    savedPlansDesc: "Rencana kebugaran AI yang telah kamu buat sebelumnya.",
    noSavedPlans: "Belum ada rencana tersimpan.",
    generateFirst: "Buat Rencana Pertamamu",
    view: "Lihat",
    planDeleted: "Rencana dihapus",
    planRenamed: "Rencana diganti nama",
    addPlan: "+ Tambah Rencana",
    whatsappCta: "Dapatkan Bantuan Pelatih Pribadi dari Coach Surya",
    occupation: "Pekerjaan",
    occupationSelect: "Pilih pekerjaan",
    occupationStudent: "Pelajar/Mahasiswa",
    occupationOffice: "Pekerja Kantoran (Banyak Duduk)",
    occupationField: "Pekerja Lapangan (Aktif Fisik)",
    occupationFreelancer: "Freelancer",
    occupationBusiness: "Pemilik Usaha",
    occupationOtherPlaceholder: "Masukkan pekerjaan Anda",
    trainingFrequency: "Hari Latihan / Minggu",
    freq2: "2 Hari",
    freq3: "3 Hari",
    freq4: "4 Hari",
    freq5: "5 Hari",
    freq6: "6 Hari",
    freq7: "7 Hari",
    downloadProgress: "Unduh Progres",
    shareProgress: "Bagikan",
    delete: "Hapus",
    confirmDelete: "Apakah Anda yakin?",

    // Settings
    settingsLanguage: "Bahasa",
    active: "Aktif",
    inactive: "Tidak Aktif",
    switchPlan: "Beralih ke rencana ini",
    createNewPlan: "Buat Rencana Baru",
    noPlansYet: "Belum ada rencana. Buat rencana kebugaran AI pertamamu!",
    planSwitched: "Rencana dialihkan!",
    languageChanged: "Bahasa diubah!",
    duration: "Durasi",
    foodStyle: "Gaya Makanan",

    // ProgressDownloadCard
    progressReport: "Laporan Progres",
    nameLabel: "Nama",
    programLabel: "Program",
    durationLabel: "Durasi",
    weightLabelShort: "Berat",
    bmiLabel: "IMT",
    calorieTargetLabel: "Target Kalori",
    motCompleted: "Kamu Membangun Ini. Disiplin Menang. 🔥",
    motInProgress: "Terus dorong menuju tujuanmu! 💪",
    eliteCompleted: "🏆 ELITE SELESAI",
    consistency: "Konsistensi",
    generatedBy: "Dibuat oleh Surya-FitAi",
    copied: "Tersalin!",
    copyCaption: "Salin Keterangan",
    failedToSave: "Gagal menyimpan",

    // NotFound
    notFoundTitle: "404",
    notFoundDesc: "Ups! Halaman tidak ditemukan",
    returnHome: "Kembali ke Beranda",

    // Enhanced Form - Sections
    basicInfoSection: "Informasi Pribadi",
    trainingConfigSection: "Konfigurasi Latihan",
    lifestyleSection: "Gaya Hidup & Pemulihan",
    nutritionSection: "Preferensi Nutrisi",

    // Enhanced Form - Why tooltip header
    whyWeAsk: "Mengapa kami menanyakan ini?",

    // Enhanced Form - Session Duration
    sessionDurationLabel: "Durasi Sesi (menit)",
    whySessionDuration: "Ini membantu kami menghitung jumlah latihan dan set yang tepat agar workout kamu pas dengan waktu yang tersedia. 60 menit adalah durasi ideal untuk kebanyakan orang.",
    minutes: "mnt",

    // Enhanced Form - Equipment
    equipmentLabel: "Peralatan Tersedia",
    whyEquipment: "Kami hanya akan sarankan latihan yang benar-benar bisa kamu lakukan dengan peralatan yang tersedia. Pilih semua yang berlaku.",
    equipBodyweight: "Berat Badan Saja",
    equipDumbbell: "Dumbbell Saja",
    equipFullGym: "Gym Lengkap",
    equipHomeBarbell: "Gym Rumah + Barbell",
    equipBands: "Resistance Band",
    equipNone: "Tidak Ada",

    // Enhanced Form - Daily Steps
    dailyStepsLabel: "Langkah Harian / Tingkat Aktivitas",
    whyDailySteps: "Aktivitas harian mempengaruhi kebutuhan kalori (NEAT). Lebih banyak langkah = TDEE lebih tinggi.",
    steps0: "< 4.000 langkah (Tidak Aktif)",
    steps1: "4.000 – 8.000 langkah (Ringan)",
    steps2: "8.000 – 12.000 langkah (Sedang)",
    steps3: "> 12.000 langkah (Sangat Aktif)",
    stepsDesk: "Kerja meja 8+ jam",

    // Enhanced Form - Sleep
    sleepHoursLabel: "Rata-rata Tidur (jam)",
    whySleep: "Kualitas tidur mempengaruhi pemulihan, keseimbangan hormon, dan kapasitas latihan.",
    sleepQualityLabel: "Kualitas Tidur",

    // Enhanced Form - Stress
    stressLevelLabel: "Tingkat Stres Saat Ini",
    whyStress: "Stres tinggi meningkatkan kortisol, memerlukan penyesuaian volume dan pemulihan.",
    nightShiftLabel: "Kerja shift malam / lembur",

    // Enhanced Form - Nutrition
    mealFrequencyLabel: "Frekuensi Makan Pilihan",
    meals3: "3 kali/hari",
    meals4: "4 kali/hari",
    meals5: "5 kali/hari",
    meals6: "6 kali/hari",
    ifLabel: "Puasa Intermiten 16/8",
    whyIF: "Jendela makan 12:00 – 20:00. Membantu pembakaran lemak dan sensitivitas insulin.",

    // Enhanced Form - Live Metrics
    liveMetricsTitle: "Metrik Terhitung Anda",
    targetCalories: "Target Kal",
    carbsLabel: "Karbo",
    fatLabel: "Lemak",
    bmiCatUnderweight: "Kurus",
    bmiCatNormal: "Normal",
    bmiCatOverweight: "Kelebihan Berat",
    bmiCatObese: "Obesitas",

    // Diet Type
    dietTypeLabel: "Tipe Diet *",
    dietTypePlaceholder: "Pilih tipe diet",
    dietOmnivore: "Omnivora",
    dietVegetarian: "Vegetarian",
    dietVegan: "Vegan",

    // Week Selector
    selectWeekLabel: "Pilih Minggu",
    weekLabel: "Minggu",

    // Exercise Detail Popup
    tipsLabel: "Tips",
    weightRecommendation: "Rekomendasi Beban",
    notesLabel: "Catatan",
    restDayTitle: "Istirahat & Pemulihan",
    restDayTip: "Fokus pada mobilitas, nutrisi, atau jalan santai hari ini.",

    // Enhanced Results
    sessionTimeBanner: "Waktu sesi cocok: {minutes} menit (5 mnt pemanasan + angkat beban + 5 mnt pendinginan)",
    warmUpLabel: "Pemanasan",
    coolDownLabel: "Pendinginan",
    weeklySplitLabel: "Pembagian Mingguan",
    tempoLabel: "Tempo",
    alternativeLabel: "Alternatif",
    warningsLabel: "Peringatan",
    recoveryTipsLabel: "Tips Pemulihan",
    deloadWeekLabel: "Minggu Deload",
    progressionRulesLabel: "Aturan Progres",
    programDuration: "Durasi Program",
    weeksLabel: "minggu",
    draftRestored: "Rencana terakhir berhasil dipulihkan.",

    // Coach Surya persona
    coachCertified: "Pelatih Pribadi Bersertifikat",
    coachExperience: "🌏 10+ Tahun • Klien Global",
    coachSubtitle: "Dirancang oleh Coach Surya — dipercaya klien di Asia Tenggara & seluruh dunia.",
    programsDescCoach: "Setiap program dirancang khusus oleh Coach Surya, berdasarkan keahlian mendalam dalam fitness coaching dan perencanaan nutrisi. Pilih yang sesuai dengan tujuanmu.",
    coachProgramPill: "Coach Surya • Pelatih Pribadi Bersertifikat",
    coachFormIntro: "Coach Surya membutuhkan detail ini untuk membangun program sempurna untukmu. Semakin akurat informasimu, semakin presisi program yang akan disesuaikan dengan tubuh dan gaya hidupmu.",
    coachMetricsSubtitle: "Coach Surya akan menggunakan angka-angka ini untuk mengkalibrasi target latihan dan nutrisi yang tepat untukmu.",
    coachGenerateHelper: "AI Coach Surya akan menganalisis semua datamu dan membangun program yang dikalibrasi khusus untukmu",
    coachPreparedBy: "Disiapkan oleh Coach Surya",
    coachCredential: "Pelatih Bersertifikat & Ahli Gizi",
    coachCardTitle: "Coach Surya",
    coachCardSubtitle: "Pelatih Pribadi & Ahli Gizi Olahraga",
    coachCalibration: "⚙️ Kalibrasi Program Coach",
    coachWeeklySplitSub: "Struktur latihan yang direkomendasikan Coach Surya untuk tujuan dan jadwalmu",
    coachWorkoutActivitySub: "Coach Surya memantau konsistensimu. Setiap sesi itu berarti.",
    coachProgressionLabel: "Protokol Progressive Overload Coach Surya",
    coachCompletedDay: "💪 Kerja bagus! Coach Surya bangga dengan konsistensimu.",
    coachRestTip: "— Coach Surya menyarankan: hidrasi yang baik dan prioritaskan tidur malam ini.",
    coachProgressMonitor: "Coach Surya memantau progressmu sepanjang program ini.",
    coachWeightChartSub: "Catat beratmu secara rutin agar Coach Surya bisa melacak perkembangan nyatamu.",
    coachCheckInSub: "Data check-in kamu membantu Coach Surya mengkalibrasi programmu seiring waktu.",
    coachHistorySub: "Perjalanan progressmu yang dipantau Coach Surya.",
    whatsappCtaCoach: "Konsultasi Langsung dengan Coach Surya",
    monthlyPlanHelper: "Program dimulai 1 bulan. Setelah selesai, kamu bisa lanjut ke bulan berikutnya atau mulai program baru.",
    monthBadge: "Bulan",
    activePlanWarning: "Kamu masih punya program aktif yang belum selesai. Selesaikan dulu atau pilih slot plan yang berbeda.",
    extendingPlan: "Membuat program bulan berikutnya...",
    extendError: "Gagal memperpanjang program. Silakan coba lagi.",
    activeBadgeLabel: "Sedang Berjalan",
    completedBadgeLabel: "Selesai",
  },
  zh: {
    // Common
    back: "返回",
    backToPrograms: "返回项目",
    home: "首页",

    // Nav
    myPlans: "我的计划",
    progress: "进度",
    signOut: "退出",
    signIn: "登录",

    // Hero
    aiPowered: "AI驱动训练",
    heroTitle1: "您的专属",
    heroTitle2: "智能教练",
    heroDesc: "获取完全个性化的锻炼计划、营养指南和采购清单——由Coach Surya在几秒内生成，根据你的身体和目标量身定制。",
    startProgram: "开始我的计划",

    // Features
    howItWorks: "如何",
    works: "运作",
    feature1Title: "选择你的项目",
    feature1Desc: "从初学者、增肌、减脂或老年健身项目中选择适合你的需求。",
    feature2Title: "AI分析你",
    feature2Desc: "我们的AI引擎处理你的身体数据、目标和限制，创建完美计划。",
    feature3Title: "获取你的计划",
    feature3Desc: "获得完整的锻炼时间表、饮食计划、采购清单和进度目标。",

    // CTA
    readyTransform: "准备好改变了吗？",
    ctaDesc: "加入数千名已经使用AI更快实现健身目标的人。",
    getStarted: "免费开始",

    // Footer
    rights: "© 2026 版权所有",

    // Programs page
    chooseYour: "选择你的",
    program: "项目",
    programsDesc: "选择与你健身目标匹配的项目。我们的AI将为你创建完全个性化的计划。",

    // Program cards
    beginnerTitle: "初学者计划",
    beginnerDesc: "适合刚接触健身和健康生活方式的人。通过指导练习建立坚实基础。",
    beginnerBenefits: ["学习正确姿势", "建立基础力量", "建立习惯", "营养基础"],
    beginnerGoal: "建立健身基础",
    bulkingTitle: "增肌计划",
    bulkingDesc: "通过高容量训练和热量盈余计划最大化肌肉增长。",
    bulkingBenefits: ["肌肉肥大", "渐进超负荷", "高蛋白饮食", "恢复优化"],
    bulkingGoal: "增加肌肉量",
    cuttingTitle: "减脂计划",
    cuttingDesc: "减少体脂同时保持肌肉。通过战略性训练和营养变得精瘦。",
    cuttingBenefits: ["聚焦减脂", "保持肌肉", "热量赤字饮食", "HIIT整合"],
    cuttingGoal: "减脂变精瘦",
    seniorTitle: "老年健身",
    seniorDesc: "为老年人设计的安全、适应性锻炼。专注于活动能力、平衡和功能性力量。",
    seniorBenefits: ["关节友好练习", "平衡训练", "柔韧性重点", "安全进阶"],
    seniorGoal: "提高活动能力和力量",

    // ProgramForm
    tellUs: "告诉我们关于你的信息，以便AI为你创建个性化计划。",
    fullName: "全名 *",
    age: "年龄 *",
    gender: "性别 *",
    genderSelect: "选择",
    male: "男",
    female: "女",
    other: "其他",
    weightKg: "体重 (kg) *",
    heightCm: "身高 (cm) *",
    fitnessGoal: "健身目标",
    fitnessGoalPlaceholder: "建立健身基础 / 减脂增肌",
    trainingDuration: "训练时长",
    experienceLevel: "经验水平",
    beginner: "初学者",
    intermediate: "中级",
    advanced: "高级",
    weeks2: "2周",
    month1: "1个月",
    months3: "3个月",
    limitations: "身体限制或伤病（可选）",
    limitationsPlaceholder: "例如：膝盖受伤、腰痛...",
    allergies: "食物过敏（可选）",
    allergiesPlaceholder: "例如：坚果、乳制品、麸质...",
    generatePlan: "生成我的计划",
    generating: "正在生成你的计划...",
    generatingStep1: "分析您的资料...",
    generatingStep2: "制定训练计划...",
    generatingStep3: "规划饮食方案...",
    generatingStep4: "完善您的专属方案...",
    fillRequired: "请填写所有必填项",
    planErrTimeout: "计划生成时间较长。请再次点击\"创建我的计划\"重试。",
    planErrParse: "AI 响应解析失败。请再次点击\"创建我的计划\"重试。",
    planErrInternal: "出现错误。请稍后再试。",
    planErrNetwork: "连接错误。请检查网络后重试。",
    planErrRate: "请求过于频繁。请稍后再试。",
    planErrCredits: "AI 使用额度已用尽。请联系支持。",
    retry: "重试",
    trainingStartDate: "训练开始日期 *",
    pickDate: "选择日期",

    // Food Style
    foodStyleLabel: "食物来源风格 *",
    foodStylePlaceholder: "选择食物风格",
    foodStyleLocal: "当地传统食物（基于我的国家）",
    foodStyleWestern: "西式风格",
    foodStyleAsian: "亚洲风格",
    foodStyleHighProtein: "高蛋白健身风格",
    foodStyleBudget: "经济实惠的当地食物",
    foodStylePremium: "优质/全食物为主",

    // Results
    yourPersonalized: "您的专属",
    aiPlan: "训练方案",
    heyUser: "你好 {name}！这是你的定制 {type} 计划。",
    hereCustom: "这是你的定制 {type} 计划。",
    dailyCalories: "每日热量",
    protein: "蛋白质",
    carbsFat: "碳水/脂肪",
    water: "水",
    exportPdf: "导出PDF",
    savePlan: "保存计划",
    saved: "已保存",
    signInToSave: "登录以保存计划",
    signInToSaveDesc: "创建账户以随时保存和访问你的计划。",
    planSaved: "计划已保存！",
    errorSaving: "保存计划出错",
    workoutPlan: "锻炼计划",
    mealPlan: "饮食计划",
    groceryList: "采购清单",
    infoSafety: "信息与安全",
    weeklyGrocery: "每周采购清单",
    progressProjection: "进度预测",
    safetyNotes: "安全注意事项",
    weeklySchedule: "每周时间表",
    estimatedCalories: "预计每次训练燃烧 {count} 卡路里",
    noPlanData: "未找到计划数据。",
    goBackPrograms: "返回项目",
    rest: "休息",
    done: "完成",
    progressTab: "进度",

    // Progress
    progressTracker: "进度",
    tracker: "追踪器",
    progressDesc: "记录每周体重并追踪你的变化。",
    start: "起始",
    current: "当前",
    change: "变化",
    weightOverTime: "体重趋势",
    logAtLeast2: "记录至少2次打卡查看进度图表。",
    logCheckIn: "记录打卡",
    date: "日期",
    weightLabel: "体重 (kg)",
    noteOptional: "备注（可选）",
    notePlaceholder: "感觉很棒！",
    addCheckIn: "添加打卡",
    checkInLogged: "打卡已记录！",
    validWeight: "请输入有效体重（20-500 kg）",
    history: "历史记录",

    // Workout Activity
    workoutActivity: "锻炼活动",
    today: "今天",
    exercises: "练习",
    streak: "连续",
    day: "天",
    days: "天",
    thisWeek: "本周",
    total: "总计",
    activeDays: "活跃天数",
    noCompletions: "还没有完成的锻炼。保存计划并开始勾选练习！",
    completed: "已完成",

    // Auth
    welcomeBack: "欢迎回来",
    createAccount: "创建账户",
    signInAccess: "登录以访问你的已保存计划",
    signUpSave: "注册以保存计划和追踪进度",
    displayName: "显示名称",
    email: "邮箱 *",
    password: "密码 *",
    signUp: "注册",
    dontHaveAccount: "没有账户？",
    alreadyHaveAccount: "已有账户？",
    welcomeBackToast: "欢迎回来！",
    accountCreated: "账户已创建！",
    checkEmail: "请查收邮件验证你的账户。",

    // Saved Plans
    savedPlans: "已保存",
    plans: "计划",
    savedPlansDesc: "你之前生成的AI健身计划。",
    noSavedPlans: "还没有保存的计划。",
    generateFirst: "生成你的第一个计划",
    view: "查看",
    planDeleted: "计划已删除",
    planRenamed: "计划已重命名",
    addPlan: "+ 添加计划",
    whatsappCta: "获取Surya教练的私人训练协助",
    occupation: "职业",
    occupationSelect: "选择职业",
    occupationStudent: "学生",
    occupationOffice: "办公室职员（久坐）",
    occupationField: "户外工作者（体力活跃）",
    occupationFreelancer: "自由职业者",
    occupationBusiness: "企业主",
    occupationOtherPlaceholder: "输入你的职业",
    trainingFrequency: "每周训练天数",
    freq2: "2天",
    freq3: "3天",
    freq4: "4天",
    freq5: "5天",
    freq6: "6天",
    freq7: "7天",
    downloadProgress: "下载进度",
    shareProgress: "分享",
    delete: "删除",
    confirmDelete: "你确定吗？",

    // Settings
    settingsLanguage: "语言",
    active: "活跃",
    inactive: "未活跃",
    switchPlan: "切换到此计划",
    createNewPlan: "创建新计划",
    noPlansYet: "还没有计划。创建你的第一个AI健身计划！",
    planSwitched: "计划已切换！",
    languageChanged: "语言已更改！",
    duration: "时长",
    foodStyle: "食物风格",

    // ProgressDownloadCard
    progressReport: "进度报告",
    nameLabel: "姓名",
    programLabel: "项目",
    durationLabel: "时长",
    weightLabelShort: "体重",
    bmiLabel: "BMI",
    calorieTargetLabel: "热量目标",
    motCompleted: "你成就了这一切。自律获胜。🔥",
    motInProgress: "继续朝着目标前进！💪",
    eliteCompleted: "🏆 精英完成",
    consistency: "坚持度",
    generatedBy: "由 Surya-FitAi 生成",
    copied: "已复制！",
    copyCaption: "复制文案",
    failedToSave: "保存失败",

    // NotFound
    notFoundTitle: "404",
    notFoundDesc: "哎呀！页面未找到",
    returnHome: "返回首页",

    // Enhanced Form - Sections
    basicInfoSection: "个人信息",
    trainingConfigSection: "训练配置",
    lifestyleSection: "生活方式与恢复",
    nutritionSection: "营养偏好",

    // Enhanced Form - Why tooltip header
    whyWeAsk: "为什么我们要问这个？",

    // Enhanced Form - Session Duration
    sessionDurationLabel: "训练时长（分钟）",
    whySessionDuration: "这能帮助我们精确计算练习数量和组数，让你的训练完美适配可用时间。60分钟是大多数人的理想时长。",
    minutes: "分钟",

    // Enhanced Form - Equipment
    equipmentLabel: "可用器材",
    whyEquipment: "我们只会推荐你实际能用现有器材完成的动作。请勾选所有适用的选项。",
    equipBodyweight: "仅自重",
    equipDumbbell: "仅哑铃",
    equipFullGym: "完整健身房",
    equipHomeBarbell: "家庭健身房+杠铃",
    equipBands: "弹力带",
    equipNone: "无器材",

    // Enhanced Form - Daily Steps
    dailyStepsLabel: "每日步数 / 活动水平",
    whyDailySteps: "日常活动影响热量需求（NEAT）。步数越多 = TDEE越高。",
    steps0: "< 4,000 步（久坐）",
    steps1: "4,000 – 8,000 步（轻度）",
    steps2: "8,000 – 12,000 步（中度）",
    steps3: "> 12,000 步（非常活跃）",
    stepsDesk: "久坐办公 8+ 小时",

    // Enhanced Form - Sleep
    sleepHoursLabel: "平均睡眠（小时）",
    whySleep: "睡眠质量影响恢复、激素平衡和训练能力。",
    sleepQualityLabel: "睡眠质量",

    // Enhanced Form - Stress
    stressLevelLabel: "当前压力水平",
    whyStress: "高压力增加皮质醇，需要调整训练量和恢复。",
    nightShiftLabel: "夜班 / 加班工作",

    // Enhanced Form - Nutrition
    mealFrequencyLabel: "首选用餐频率",
    meals3: "每天3餐",
    meals4: "每天4餐",
    meals5: "每天5餐",
    meals6: "每天6餐",
    ifLabel: "16/8间歇性禁食",
    whyIF: "进食窗口12:00–20:00。有助于减脂和胰岛素敏感性。",

    // Enhanced Form - Live Metrics
    liveMetricsTitle: "您的计算指标",
    targetCalories: "目标热量",
    carbsLabel: "碳水",
    fatLabel: "脂肪",
    bmiCatUnderweight: "偏瘦",
    bmiCatNormal: "正常",
    bmiCatOverweight: "超重",
    bmiCatObese: "肥胖",

    // Diet Type
    dietTypeLabel: "饮食类型 *",
    dietTypePlaceholder: "选择饮食类型",
    dietOmnivore: "杂食者",
    dietVegetarian: "素食者",
    dietVegan: "纯素者",

    // Week Selector
    selectWeekLabel: "选择周",
    weekLabel: "第",

    // Exercise Detail Popup
    tipsLabel: "技巧",
    weightRecommendation: "重量建议",
    notesLabel: "备注",
    restDayTitle: "休息与恢复",
    restDayTip: "今天专注于灵活性训练、营养或轻松散步。",

    // Enhanced Results
    sessionTimeBanner: "训练时间匹配：{minutes} 分钟（5分钟热身 + 力量训练 + 5分钟拉伸）",
    warmUpLabel: "热身",
    coolDownLabel: "拉伸放松",
    weeklySplitLabel: "每周安排",
    tempoLabel: "节奏",
    alternativeLabel: "替代动作",
    warningsLabel: "警告",
    recoveryTipsLabel: "恢复建议",
    deloadWeekLabel: "减负周",
    progressionRulesLabel: "进阶规则",
    programDuration: "计划时长",
    weeksLabel: "周",
    draftRestored: "已恢复您上次生成的计划。",

    // Coach Surya persona
    coachCertified: "认证私人教练",
    coachExperience: "🌏 10年以上 • 全球客户",
    coachSubtitle: "由Surya教练设计 — 深受东南亚及全球客户信赖。",
    programsDescCoach: "每个计划均由Coach Surya亲自设计，基于对健身指导与营养规划的深入专业知识。选择适合您目标的计划。",
    coachProgramPill: "Surya教练 • 认证私人教练",
    coachFormIntro: "Surya教练需要这些详细信息来为您制定完美计划。您的信息越准确，您的计划就会越精准地针对您的身体和生活方式进行调整。",
    coachMetricsSubtitle: "Surya教练将使用这些数字来精确校准您的训练和营养目标。",
    coachGenerateHelper: "Surya教练的AI将分析您的所有数据，为您专门制定精准计划",
    coachPreparedBy: "由Surya教练准备",
    coachCredential: "认证私人教练及运动营养师",
    coachCardTitle: "Coach Surya",
    coachCardSubtitle: "私人教练及运动营养师",
    coachCalibration: "⚙️ 教练程序校准",
    coachWeeklySplitSub: "Surya教练根据您的目标和时间表推荐的训练结构",
    coachWorkoutActivitySub: "Surya教练正在追踪您的坚持程度。每次训练都很重要。",
    coachProgressionLabel: "Surya教练的渐进超负荷方案",
    coachCompletedDay: "💪 干得好！Surya教练为您的坚持感到骄傲。",
    coachRestTip: "— Surya教练建议：今晚好好补水并优先保证睡眠。",
    coachProgressMonitor: "Surya教练全程监督您的进度。",
    coachWeightChartSub: "定期记录您的体重，以便Surya教练跟踪您的真实进度。",
    coachCheckInSub: "您的打卡数据有助于Surya教练随时间调整您的计划。",
    coachHistorySub: "由Surya教练记录的您的进度之旅。",
    whatsappCtaCoach: "获得Coach Surya的一对一指导",
    monthlyPlanHelper: "计划从1个月开始。完成后，您可以延续到下个月或重新开始。",
    monthBadge: "第",
    activePlanWarning: "您还有一个未完成的活跃计划。请先完成或选择其他计划槽位。",
    extendingPlan: "正在生成下个月的计划...",
    extendError: "延续计划失败。请重试。",
    activeBadgeLabel: "进行中",
    completedBadgeLabel: "已完成",
  },
};

type Translations = { [K in keyof typeof translations.en]: (typeof translations.en)[K] extends string[] ? string[] : string };

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("fitai-lang");
    if (saved === "id" || saved === "en" || saved === "zh") return saved;
    return "id";
  });

  const handleSetLang = (newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("fitai-lang", newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] as Translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
