export const PRICING_TEXT = {
  en: {
    sectionTitle: 'Simple, Transparent Pricing',
    sectionSubtitle: "Start free. Upgrade when you're ready.",
    badge: '50% OFF — Limited Time',
    planName: 'Pro Plan',
    normalPrice: 'Rp 39,900',
    promoPrice: 'Rp 19,900',
    perMonth: '/ month',
    trialLabel: '14-Day Free Trial',
    trialDesc: 'Full access, no credit card required',
    ctaButton: 'Start Free Trial',
    ctaLoggedIn: 'Upgrade to Pro',
    features: [
      '✅ Generate unlimited AI workout plans',
      '✅ Personalized meal plans & grocery lists',
      '✅ Save up to 3 plans',
      '✅ Progress tracking',
      '✅ All future features included',
    ],
    disclaimer: 'Cancel anytime. Questions? Contact us at fitaisurya@gmail.com',
    trialNote: 'After trial ends, subscribe for Rp 19,900/month to keep saving plans.',
  },
  id: {
    sectionTitle: 'Harga Sederhana & Transparan',
    sectionSubtitle: 'Mulai gratis. Upgrade kapan saja.',
    badge: 'DISKON 50% — Waktu Terbatas',
    planName: 'Paket Pro',
    normalPrice: 'Rp 39.900',
    promoPrice: 'Rp 19.900',
    perMonth: '/ bulan',
    trialLabel: 'Uji Coba Gratis 14 Hari',
    trialDesc: 'Akses penuh, tanpa kartu kredit',
    ctaButton: 'Mulai Uji Coba Gratis',
    ctaLoggedIn: 'Upgrade ke Pro',
    features: [
      '✅ Generate program AI tanpa batas',
      '✅ Rencana makan & daftar belanja personal',
      '✅ Simpan hingga 3 program',
      '✅ Pelacakan progres latihan',
      '✅ Semua fitur baru termasuk',
    ],
    disclaimer: 'Batalkan kapan saja. Pertanyaan? Hubungi fitaisurya@gmail.com',
    trialNote: 'Setelah trial berakhir, berlangganan Rp 19.900/bulan untuk tetap bisa menyimpan program.',
  },
  zh: {
    sectionTitle: '简单透明的定价',
    sectionSubtitle: '免费开始，随时升级。',
    badge: '限时折扣50%',
    planName: 'Pro计划',
    normalPrice: 'Rp 39,900',
    promoPrice: 'Rp 19,900',
    perMonth: '/ 月',
    trialLabel: '14天免费试用',
    trialDesc: '完整功能，无需信用卡',
    ctaButton: '开始免费试用',
    ctaLoggedIn: '升级到Pro',
    features: [
      '✅ 无限生成AI训练计划',
      '✅ 个性化饮食计划和购物清单',
      '✅ 保存最多3个计划',
      '✅ 训练进度追踪',
      '✅ 包含所有未来功能',
    ],
    disclaimer: '随时取消。有疑问？请联系 fitaisurya@gmail.com',
    trialNote: '试用结束后，每月Rp 19,900订阅即可继续保存计划。',
  },
} as const;

export type PricingLang = keyof typeof PRICING_TEXT;
