import { useState } from "react";
import { Download, Share2, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import html2canvas from "html2canvas";
import logoSrc from "@/assets/logo.png";

interface ProgressDownloadProps {
  userName: string;
  programName: string;
  duration: string;
  weight: number;
  bmi: string;
  calorieTarget: number;
  progressPercent: number;
  weeklyAdherence?: number;
}

export default function ProgressDownloadCard({
  userName,
  programName,
  duration,
  weight,
  bmi,
  calorieTarget,
  progressPercent,
  weeklyAdherence = 92,
}: ProgressDownloadProps) {
  const { t } = useLanguage();
  const [showShare, setShowShare] = useState(false);
  const [captionCopied, setCaptionCopied] = useState(false);
  const isComplete = progressPercent >= 100;

  const pct = Math.min(progressPercent, 100);
  const motText = isComplete
    ? t.motCompleted.replace(/[^\w\s.,!?'"()-]/g, "").trim()
    : t.motInProgress.replace(/[^\w\s.,!?'"()-]/g, "").trim();

  const shareCaption = isComplete
    ? "I just completed my training program with Surya-FitAi.\nConsistency. Discipline. Results.\n#SuryaFitAi #ProgressComplete #FitnessJourney"
    : "Making progress every day with Surya-FitAi\n#SuryaFitAi #FitnessJourney";

  const now = new Date();
  const dateStr = `${String(now.getDate()).padStart(2, "0")}/${String(now.getMonth() + 1).padStart(2, "0")}/${now.getFullYear()}`;

  const stats = [
    { label: t.nameLabel, value: userName },
    { label: t.programLabel, value: programName },
    { label: t.durationLabel, value: duration },
    { label: t.weightLabelShort, value: `${weight} kg` },
    { label: t.bmiLabel, value: bmi },
    { label: t.calorieTargetLabel, value: `${calorieTarget} kcal` },
  ];

  const generateImage = async (): Promise<Blob> => {
    const GREEN = "#16a34a";
    const GREY = "#8a8a9a";
    const SURFACE = "#121216";

    const statsHTML = stats
      .map(
        (s) => `
      <div style="background:${SURFACE};border-radius:8px;padding:12px 14px;flex:1 1 calc(50% - 6px);min-width:0;">
        <div style="font-size:11px;color:${GREY};margin-bottom:4px;text-transform:uppercase;letter-spacing:0.5px;">${s.label}</div>
        <div style="font-size:16px;font-weight:700;color:#f0f0f5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${s.value}</div>
      </div>`
      )
      .join("");

    const html = `
      <div style="text-align:center;margin-bottom:20px;">
        <img src="${logoSrc}" style="height:40px;width:auto;object-fit:contain;margin:0 auto 8px;display:block;" crossorigin="anonymous" />
        <div style="font-size:18px;font-weight:800;color:#fff;letter-spacing:0.5px;">Surya-FitAi</div>
        <div style="font-size:13px;color:${GREY};margin-top:4px;">${t.progressReport}</div>
        <div style="display:inline-block;background:${GREEN}22;border:1px solid ${GREEN}44;border-radius:20px;padding:3px 14px;margin-top:8px;">
          <span style="font-size:11px;color:${GREEN};font-weight:600;">Prepared by Coach Surya</span>
        </div>
      </div>
      <div style="height:1px;background:linear-gradient(90deg,transparent,${GREEN},transparent);margin-bottom:20px;"></div>
      <div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:24px;">${statsHTML}</div>
      <div style="text-align:center;margin-bottom:20px;">
        <div style="font-size:12px;color:${GREY};text-transform:uppercase;letter-spacing:1px;margin-bottom:6px;">Workout Completion</div>
        <div style="font-size:36px;font-weight:800;color:#fff;margin-bottom:10px;">${pct}%</div>
        <div style="background:#1a1a20;border-radius:6px;height:12px;overflow:hidden;">
          <div style="width:${pct}%;height:100%;background:${GREEN};border-radius:6px;"></div>
        </div>
      </div>
      <div style="border:1px solid ${GREEN}44;border-radius:8px;padding:12px 16px;text-align:center;margin-bottom:20px;">
        <div style="font-size:13px;color:${GREEN};font-style:italic;">${motText}</div>
      </div>
      <div style="text-align:center;">
        <div style="font-size:11px;color:${GREY};">Generated by Surya-FitAi &bull; Coach Surya</div>
        <div style="font-size:11px;color:${GREEN};margin-top:2px;">${dateStr}</div>
      </div>`;

    const container = document.createElement("div");
    container.style.cssText = "position:fixed;left:-9999px;top:0;z-index:-1;";
    document.body.appendChild(container);

    const el = document.createElement("div");
    el.style.cssText = `width:540px;padding:32px;background:#0a0a0d;border-radius:16px;font-family:'Inter','Segoe UI',system-ui,sans-serif;color:#fff;`;
    el.innerHTML = html;
    container.appendChild(el);

    // Wait for images
    const imgs = el.querySelectorAll("img");
    await Promise.all(
      Array.from(imgs).map(
        (img) =>
          new Promise<void>((res) => {
            if (img.complete && img.naturalHeight > 0) return res();
            img.onload = () => res();
            img.onerror = () => res();
          })
      )
    );

    const scale = (window.devicePixelRatio || 1) * 2;
    const canvas = await html2canvas(el, {
      scale,
      backgroundColor: "#0a0a0d",
      useCORS: true,
      logging: false,
    });

    document.body.removeChild(container);

    return new Promise<Blob>((resolve, reject) => {
      canvas.toBlob(
        (blob) => {
          if (blob) resolve(blob);
          else reject(new Error("Failed to create image blob"));
        },
        "image/png"
      );
    });
  };

  const handleDownload = async () => {
    try {
      const blob = await generateImage();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Surya-FitAi-Progress-${userName.replace(/\s/g, "-")}.png`;
      a.click();
      URL.revokeObjectURL(url);
      setShowShare(true);
    } catch (e) {
      console.error("Download failed:", e);
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        const blob = await generateImage();
        const file = new File([blob], "surya-fitai-progress.png", { type: "image/png" });
        await navigator.share({
          title: "My Surya-FitAi Progress",
          text: shareCaption,
          files: [file],
        });
      } catch {
        // User cancelled
      }
    } else {
      window.open(
        `https://wa.me/?text=${encodeURIComponent(shareCaption)}`,
        "_blank"
      );
    }
  };

  const handleCopyCaption = () => {
    navigator.clipboard.writeText(shareCaption);
    setCaptionCopied(true);
    setTimeout(() => setCaptionCopied(false), 2000);
  };

  return (
    <div className="space-y-3">
      <div className="flex flex-col sm:flex-row gap-2">
        <Button onClick={handleDownload} variant="secondary" size="sm">
          <Download className="w-4 h-4 mr-1" /> {t.downloadProgress || "Download Progress"}
        </Button>
        {showShare && (
          <>
            <Button onClick={handleShare} variant="secondary" size="sm">
              <Share2 className="w-4 h-4 mr-1" /> {t.shareProgress || "Share"}
            </Button>
            <Button onClick={handleCopyCaption} variant="outline" size="sm">
              {captionCopied ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
              {captionCopied ? t.copied : t.copyCaption}
            </Button>
          </>
        )}
      </div>
      {showShare && (
        <div className="bg-secondary/50 rounded-lg p-3 text-xs text-muted-foreground whitespace-pre-line border border-border/50">
          {shareCaption}
        </div>
      )}
    </div>
  );
}
