import { useRef, useState } from "react";
import { Download, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";

interface ProgressDownloadProps {
  userName: string;
  programName: string;
  duration: string;
  weight: number;
  bmi: string;
  calorieTarget: number;
  progressPercent: number;
}

export default function ProgressDownloadCard({
  userName,
  programName,
  duration,
  weight,
  bmi,
  calorieTarget,
  progressPercent,
}: ProgressDownloadProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { t } = useLanguage();
  const [showShare, setShowShare] = useState(false);

  const generateImage = (): Promise<Blob> => {
    return new Promise((resolve) => {
      const canvas = document.createElement("canvas");
      canvas.width = 1080;
      canvas.height = 1350;
      const ctx = canvas.getContext("2d")!;

      // Background gradient
      const grad = ctx.createLinearGradient(0, 0, 0, 1350);
      grad.addColorStop(0, "#ffffff");
      grad.addColorStop(1, "#f0fdf4");
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, 1080, 1350);

      // Card shadow area
      ctx.fillStyle = "#f8fafc";
      ctx.beginPath();
      ctx.roundRect(60, 80, 960, 1190, 32);
      ctx.fill();
      ctx.strokeStyle = "#e2e8f0";
      ctx.lineWidth = 2;
      ctx.stroke();

      // Brand header
      ctx.fillStyle = "#39FF14";
      ctx.fillRect(60, 80, 960, 6);

      // Title
      ctx.fillStyle = "#0f172a";
      ctx.font = "bold 56px 'Space Grotesk', sans-serif";
      ctx.textAlign = "center";
      ctx.fillText("Surya-FitAi", 540, 200);

      ctx.fillStyle = "#64748b";
      ctx.font = "28px 'Inter', sans-serif";
      ctx.fillText("Progress Report", 540, 250);

      // Divider
      ctx.strokeStyle = "#e2e8f0";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(140, 290);
      ctx.lineTo(940, 290);
      ctx.stroke();

      // User info section
      const drawStat = (label: string, value: string, y: number) => {
        ctx.fillStyle = "#94a3b8";
        ctx.font = "24px 'Inter', sans-serif";
        ctx.textAlign = "left";
        ctx.fillText(label, 140, y);
        ctx.fillStyle = "#0f172a";
        ctx.font = "bold 32px 'Space Grotesk', sans-serif";
        ctx.textAlign = "right";
        ctx.fillText(value, 940, y);
      };

      drawStat("Name", userName, 360);
      drawStat("Program", programName, 430);
      drawStat("Duration", duration, 500);
      drawStat("Weight", `${weight} kg`, 570);
      drawStat("BMI", bmi, 640);
      drawStat("Calorie Target", `${calorieTarget} kcal`, 710);

      // Progress bar section
      ctx.fillStyle = "#0f172a";
      ctx.font = "bold 36px 'Space Grotesk', sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(`Progress: ${progressPercent}%`, 540, 820);

      // Progress bar background
      ctx.fillStyle = "#e2e8f0";
      ctx.beginPath();
      ctx.roundRect(140, 850, 800, 40, 20);
      ctx.fill();

      // Progress bar fill
      const progressGrad = ctx.createLinearGradient(140, 0, 940, 0);
      progressGrad.addColorStop(0, "#39FF14");
      progressGrad.addColorStop(1, "#22c55e");
      ctx.fillStyle = progressGrad;
      ctx.beginPath();
      ctx.roundRect(140, 850, Math.max(40, 800 * (progressPercent / 100)), 40, 20);
      ctx.fill();

      // Motivational text
      ctx.fillStyle = "#64748b";
      ctx.font = "italic 26px 'Inter', sans-serif";
      ctx.textAlign = "center";
      ctx.fillText("Keep pushing towards your goals! 💪", 540, 960);

      // Footer
      ctx.fillStyle = "#cbd5e1";
      ctx.font = "22px 'Inter', sans-serif";
      ctx.fillText("Generated by Surya-FitAi", 540, 1200);
      ctx.fillText(new Date().toLocaleDateString(), 540, 1240);

      canvas.toBlob((blob) => resolve(blob!), "image/jpeg", 0.95);
    });
  };

  const handleDownload = async () => {
    const blob = await generateImage();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Surya-FitAi-Progress-${userName.replace(/\s/g, "-")}.jpg`;
    a.click();
    URL.revokeObjectURL(url);
    setShowShare(true);
  };

  const handleShare = async () => {
    if (navigator.share) {
      const blob = await generateImage();
      const file = new File([blob], "surya-fitai-progress.jpg", { type: "image/jpeg" });
      try {
        await navigator.share({
          title: "My Surya-FitAi Progress",
          text: `Check out my fitness progress with Surya-FitAi! ${progressPercent}% complete 💪`,
          files: [file],
        });
      } catch {
        // User cancelled
      }
    } else {
      window.open(
        `https://wa.me/?text=${encodeURIComponent(`Check out my Surya-FitAi progress! ${progressPercent}% complete 💪`)}`,
        "_blank"
      );
    }
  };

  return (
    <div className="flex flex-col sm:flex-row gap-2">
      <Button onClick={handleDownload} variant="secondary" size="sm">
        <Download className="w-4 h-4 mr-1" /> {t.downloadProgress || "Download Progress"}
      </Button>
      {showShare && (
        <Button onClick={handleShare} variant="secondary" size="sm">
          <Share2 className="w-4 h-4 mr-1" /> {t.shareProgress || "Share"}
        </Button>
      )}
    </div>
  );
}
